[package]
name = "noheap-collections"
version = "0.1.0"
edition = "2021"

[dependencies]
generic-array = "1.0.0"
typenum = "1.17.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "main"
harness = false

[profile.bench]
lto = 'fat'

[profile.release]
lto = 'fat'
